"""create initial schema

Revision ID: ce42dbb568fe
Revises: 
Create Date: 2026-08-24 15:39:52.448555
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'ce42dbb568fe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_user_id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conference_record_name', sa.String(length=255), nullable=False),
    sa.Column('meeting_space_name', sa.String(length=255), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='in_progress', nullable=False),
    sa.Column('transcript_status', sa.String(length=50), server_default='not_available', nullable=False),
    sa.Column('ai_status', sa.String(length=50), server_default='NOT_PROCESSED', nullable=False),
    sa.Column('ai_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sheets_sync_status', sa.String(length=50), server_default='NOT_SYNCED', nullable=False),
    sa.Column('dom_capture_status', sa.String(length=50), server_default='not_captured', nullable=False),
    sa.Column('dom_transcript_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('comparison_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conference_record_name')
    )
    op.create_index('idx_meetings_start_time', 'meetings', ['start_time'], unique=False)
    op.create_index('idx_meetings_user_id', 'meetings', ['user_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('google_participant_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('participant_type', sa.String(length=50), server_default='signed_in_user', nullable=False),
    sa.Column('join_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leave_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'google_participant_name', name='uq_participants_meeting_google_name')
    )
    op.create_index('idx_participants_meeting_id', 'participants', ['meeting_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('google_transcript_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('docs_url', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_transcript_name')
    )
    op.create_index('idx_transcripts_meeting_id', 'transcripts', ['meeting_id'], unique=False)
    op.create_table('transcript_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('google_entry_name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), server_default='google_meet', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_entry_name')
    )
    op.create_index('idx_entries_participant_id', 'transcript_entries', ['participant_id'], unique=False)
    op.create_index('idx_entries_start_time', 'transcript_entries', ['start_time'], unique=False)
    op.create_index('idx_entries_transcript_id', 'transcript_entries', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entries_transcript_id', table_name='transcript_entries')
    op.drop_index('idx_entries_start_time', table_name='transcript_entries')
    op.drop_index('idx_entries_participant_id', table_name='transcript_entries')
    op.drop_table('transcript_entries')
    op.drop_index('idx_transcripts_meeting_id', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('idx_participants_meeting_id', table_name='participants')
    op.drop_table('participants')
    op.drop_index('idx_meetings_user_id', table_name='meetings')
    op.drop_index('idx_meetings_start_time', table_name='meetings')
    op.drop_table('meetings')
    op.drop_table('users')
    # ### end Alembic commands ###

